### Segmenting and Clustering Neighborhoods in Toronto
1. Part 1

In [244]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import folium
import requests
import json
from bs4 import BeautifulSoup
import matplotlib.cm as cm
import matplotlib.colors as colors

%matplotlib inline

In [245]:
import pandas as pd # library for data analsysis
pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", None)

import json # library to handle JSON files

from geopy.geocoders import Nominatim # convert an address into latitude and longitude values

import requests # library to handle requests
from bs4 import BeautifulSoup # library to parse HTML and XML documents

from pandas.io.json import json_normalize # tranform JSON file into a pandas dataframe

# Matplotlib and associated plotting modules
import matplotlib.cm as cm
import matplotlib.colors as colors

# import k-means from clustering stage
from sklearn.cluster import KMeans

import folium # map rendering library

print("Libraries imported.")

Libraries imported.

In [246]:
data = requests.get('https://en.wikipedia.org/wiki/List_of_postal_codes_of_Canada:_M').text

In [247]:
# parse data from the html into a beautifulsoup object
soup = BeautifulSoup(data, 'html.parser')

In [248]:
# create three lists to store table data
postalCodeList = []
boroughList = []
neighborhoodList = []

In [249]:
# append the data into the respective lists
for row in soup.find('table').find_all('tr'):
    cells = row.find_all('td')
    if(len(cells) > 0):
        postalCodeList.append(cells[0].text)
        boroughList.append(cells[1].text)
        neighborhoodList.append(cells[2].text.rstrip('\n')) # avoid new lines in neighborhood cell

In [250]:
# create a new DataFrame from the three lists
toronto_df = pd.DataFrame({"PostalCode": postalCodeList,
                           "Borough": boroughList,
                           "Neighborhood": neighborhoodList})

toronto_df.head()

  PostalCode             Borough                Neighborhood
0      M1A\n      Not assigned\n
1      M2A\n      Not assigned\n
2      M3A\n        North York\n                   Parkwoods
3      M4A\n        North York\n            Victoria Village
4      M5A\n  Downtown Toronto\n  Regent Park / Harbourfront

In [251]:
toronto_df=toronto_df.replace(r'\n',  '', regex=True)
toronto_df['Borough']=toronto_df['Borough'].str.strip()
toronto_df['PostalCode']=toronto_df['PostalCode'].str.strip()
toronto_df['Neighborhood']=toronto_df['Neighborhood'].str.strip()
toronto_df.head()

  PostalCode           Borough                Neighborhood
0        M1A      Not assigned
1        M2A      Not assigned
2        M3A        North York                   Parkwoods
3        M4A        North York            Victoria Village
4        M5A  Downtown Toronto  Regent Park / Harbourfront

In [252]:
# drop cells with a borough that is Not assigned
toronto_df = toronto_df[toronto_df['Borough'] != 'Not assigned']
toronto_df.head()

  PostalCode           Borough                                  Neighborhood
2        M3A        North York                                     Parkwoods
3        M4A        North York                              Victoria Village
4        M5A  Downtown Toronto                    Regent Park / Harbourfront
5        M6A        North York             Lawrence Manor / Lawrence Heights
6        M7A  Downtown Toronto  Queen's Park / Ontario Provincial Government

In [253]:
# group neighborhoods in the same borough
toronto_df = toronto_df.groupby(["PostalCode", "Borough"], as_index=False).agg(lambda x: ", ".join(x))
toronto_df['Neighborhood']=toronto_df_grouped['Neighborhood'].replace(to_replace='/', value=',', regex=True)
toronto_df.head()

  PostalCode      Borough                              Neighborhood
0        M1B  Scarborough                           Malvern , Rouge
1        M1C  Scarborough  Rouge Hill , Port Union , Highland Creek
2        M1E  Scarborough       Guildwood , Morningside , West Hill
3        M1G  Scarborough                                    Woburn
4        M1H  Scarborough                                 Cedarbrae

In [254]:
# for Neighborhood="Not assigned", make the value the same as Borough
for index, row in toronto_df.iterrows():
    if row["Neighborhood"] == "Not assigned":
        row["Neighborhood"] = row["Borough"]
        
toronto_df.head()

  PostalCode      Borough                              Neighborhood
0        M1B  Scarborough                           Malvern , Rouge
1        M1C  Scarborough  Rouge Hill , Port Union , Highland Creek
2        M1E  Scarborough       Guildwood , Morningside , West Hill
3        M1G  Scarborough                                    Woburn
4        M1H  Scarborough                                 Cedarbrae

In [255]:
# filter only essentil Postal codes
toronto_df_req = toronto_df[toronto_df_grouped['PostalCode'].isin(["M5G", "M2H", "M4B", "M1J", "M4G", "M4M", "M1R", "M9V", "M9L", "M5V", "M1B", "M5A"])].reset_index(drop=True)
toronto_df_req

,PostalCode,Borough,Neighborhood
0,M1B,Scarborough,"Malvern , Rouge"
1,M1J,Scarborough,Scarborough Village
2,M1R,Scarborough,"Wexford , Maryvale"
3,M2H,North York,Hillcrest Village
4,M4B,East York,"Parkview Hill , Woodbine Gardens"
5,M4G,East York,Leaside
6,M4M,East Toronto,Studio District
7,M5A,Downtown Toronto,"Regent Park , Harbourfront"
8,M5G,Downtown Toronto,Central Bay Street
9,M5V,Downtown Toronto,"CN Tower , King and Spadina , Railway Lands , ..."
10,M9L,North York,Humber Summit
11,M9V,Etobicoke,"South Steeles , Silverstone , Humbergate , Jam..."

In [256]:
# print the number of rows of the cleaned dataframe
toronto_df_req.shape

(12, 3)